import '@repo/ui/index.css';
import { montserrat } from '@repo/ui/lib/fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'VNMIXX - Shop',
  description: 'Generated by create turbo',
  icons: {
    icon: [
      { url: '/images/favicon-light.png', media: '(prefers-color-scheme: light)' },
      { url: '/images/favicon-dark.png', media: '(prefers-color-scheme: dark)' },
    ],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }): React.JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
