import { COOKIE_ACCESS_TOKEN } from '@/config/constants';
import { AuthProvider } from '@/modules/auth/providers/auth-provider';
import { ShopFooter } from '@/modules/footer/components/shop-footer';
import { ShopHeader } from '@/modules/header/components/shop-header';
import { QueryProvider } from '@/providers/query-provider';
import '@/styles/globals.css';
import { Toaster } from '@repo/ui/components/ui/sonner';
import { montserrat } from '@repo/ui/lib/fonts';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Shop',
  description: 'Generated by create turbo',
  icons: {
    icon: [
      { url: '/images/favicon-light.png', media: '(prefers-color-scheme: light)' },
      { url: '/images/favicon-dark.png', media: '(prefers-color-scheme: dark)' },
    ],
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<React.JSX.Element> {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get(COOKIE_ACCESS_TOKEN)?.value ?? null;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} min-h-dvh flex flex-col`}>
        <QueryProvider>
          <AuthProvider accessToken={accessToken}>
            <ShopHeader />
            <div className="flex-1 pb-16 md:pb-0">{children}</div>
            <ShopFooter />
            <Toaster richColors closeButton position="top-center" theme="light" />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
