#!/usr/bin/env sh
files=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -n "$files" ]; then
  echo "$files" | tr '\n' '\0' | xargs -0 pnpm exec prettier --write --ignore-unknown
  git update-index --again
fi
